spring:
  application:
    name: factory
  datasource:
    url:
    username:
    password: eCjY8N7C2vExCMUps112
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect